# yml 配置中冒号后面有个空格,是语法的规定.yml可以配置多个不同环境
server:
    port: 8081
    context-path: /girl
# 使用配置文件的配置变量
# api: B
# age: 27
# content: "cupSize: ${cupSize},age:${age}"
girl:
    api: B
    age: 18

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.pojo